# docker-compose.yml (The common file)
version: '3'
services:
  node-app:
    container_name: social-network
    ports:
      - '8080:8080' # host:container, You can remove this when using nginx
    depends_on:
      - postgres # This will make sure that postgres service starts up before node
  postgres: # Use the service name and docker will map it to its IP Address
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

volumes:
  postgres-db: # Make volume to store data on the host hard drive
